### ISSUE TITLE
Explain does not show pop up with details for each phase

### ISSUE THREAD

**Issue by deniswsrosa** [couchbaselabs/couchbase_jetbrains_plugin#86]

**Comment by vijaygopal-couchbase** [comment]
The reason I like that section is because its succinct - I could  focus only on boxes I like and don’t have to parse through the entire explain plan JSON result. If I were dev and I ran a query or I implemented an index and if I am interested to see how did my index perform and see additional details, then my only way is to see the explain plan graph and manually navigate to the respective JSON section for more details. If I have to repeat that for 10 iterations to tune a query as I am still learning Couchbase, then my focus is lost in the process.

**Comment by deniswsrosa** [comment]
This fix will be available in the next release
