### ISSUE TITLE
Document count not getting updated upon adding a new document

### ISSUE THREAD

**Issue by lokesh-couchbase** [couchbaselabs/couchbase_jetbrains_plugin#92]
I tried creating a new document, however even after refreshing the documents, the document count was not updated. 

Right now to update it whole collection must be reloaded. It will be better in terms of UX if we can see the documents (upon refreshing docs) then the count must also be updated

**Comment by deniswsrosa** [comment]
@lokesh-couchbase The goal of the document count is not to be precise, but to give the user a rough idea of how many documents are there. Running counts against the database is a heavy operation, so we won't update the counts until the user refreshes the scope. It was implemented like that by design
